version: '3'
services:
  web:
    image: php:7.4-apache
    volumes:
      - ./php-login-app:/var/www/html
    ports:
      - "8081:80"
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: mydb
    ports:
      - "3306:3306"
